apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-blue
spec:
  # Blue es la version estable v1.
  replicas: 2
  selector:
    matchLabels:
      app: inventario-app
      version: v1
  template:
    metadata:
      labels:
        app: inventario-app
        version: v1
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/patrici0l/practica-ci-cd:latest
          env:
            # Estas variables permiten identificar la version en /version.
            - name: APP_VERSION
              value: "v1"
            - name: APP_COLOR
              value: "blue"
          ports:
            - containerPort: 3000
          readinessProbe:
            # El pod solo entra al Service cuando la app esta lista.
            httpGet:
              path: /health
              port: 3000
