apiVersion: v1
kind: Service
metadata:
  name: inventario-service-bg
spec:
  type: NodePort
  # Cambiar version=v1 a version=v2 mueve el trafico de Blue a Green.
  selector:
    app: inventario-app
    version: v1
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
