apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: inventario-app
  template:
    metadata:
      labels:
        app: inventario-app
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/patrici0l/practica-ci-cd:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
